name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            runner: ubuntu-latest
            cpu: amd64
            shell: bash
          - os: linux
            runner: ubuntu-latest
            cpu: i386
            shell: bash
          - os: macos
            runner: macos-13
            cpu: amd64
            shell: bash
          - os: macos
            runner: macos-14
            cpu: arm64
            shell: bash
          - os: windows
            runner: windows-latest
            cpu: amd64
            shell: msys2 {0}
        nim:
          - ref: version-2-0
          - ref: version-2-2

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    name: '${{ matrix.platform.os }}-${{ matrix.platform.cpu }} (Nim ${{ matrix.nim.ref }})'
    runs-on: ${{ matrix.platform.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nim
        uses: vacp2p/nim-libp2p/.github/actions/install_nim@master
        with:
          os: ${{ matrix.platform.os }}
          cpu: ${{ matrix.platform.cpu }}
          shell: ${{ matrix.platform.shell }}
          nim_ref: ${{ matrix.nim.ref }}

      - name: Install deps (windows)
        if : ${{ matrix.platform.os == 'windows'}}
        run: |
          pacman -S --noconfirm base-devel gcc mingw-w64-x86_64-openssl

      - name: Install dependencies
        run: nimble install -y

      - name: Test
        run: nimble test -y
